name: clean_architecture_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # general
  equatable: ^2.0.5
  google_fonts: ^5.1.0

  # dependency injection
  get_it: ^7.6.4

  # requests
  http: ^1.1.0

  # state management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
